/*

molecules for the HP model

1 : HPHHPPHHHHPHHHPPHHPPHPHHHPHPHHPPHHPPPHPPPPPPPPHH - 32
2 : HHHHPHHPHHHHHPPHPPHHPPHPPPPPPHPPHPPPHPPHHPPHHHPH - 34
3 : PHPHHPHHHHHHPPHPHPPHPHHPHPHPPPHPPHHPPHHPPHPHPPHP - 34
4 : PHPHHPPHPHHHPPHHPHHPPPHHHHHPPHPHHPHPHPPPPHPPHPHP - 33
5 : PPHPPPHPHHHHPPHHHHPHHPHHHPPHPHPHPPHPPPPPPHHPHHPH - 32
6 : HHHPPPHHPHPHHPHHPHHPHPPPPPPPHPHPPHPPPHPPHHHHHHPH - 32
7 : PHPPPPHPHHHPHPHHHHPHHPHHPPPHPHPPPHHHPPHHPPHHPPPH - 32
8 : PHHPHHHPHHHHPPHHHPPPPPPHPHHPPHHPHPPPHHPHPHPHHPPP - 31
9 : PHPHPPPPHPHPHPPHPHHHHHHPPHHHPHPPHPHHPPHPHHHPPPPH - 34
10 : PHHPPPPPPHHPPPHHHPHPPHPHHPPHPPHPPHHPPHHHHHHHPPHH - 33


S1 : HPHPPHHPHPPHPHHPPHPH - 11
S2 : HHPPHPPHPPHPPHPPHPPHPPHH - 13
S3 : PPHPPHHPPPPHHPPPPHHPPPPHH - 9
S4 : PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP - 18
S5 : PPHPPHHPPHHPPPPPHHHHHHHHHHPPPPPPHHPPHHPPHPPHHHHH - 31
S6 : HHPHPHPHPHHHHPHPPPHPPPHPHHHHPHPHPHPHH - 31
S6 : HHPHPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH - 31
S7 : PPHHHPHHHHHHHHPPPHHHHHHHHHHPHPPPHHHHHHHHHHHHPPPPHHHHHHPHHPHP - 52 (54)
S8 : HHHHHHHHHHHHPHPHPPHHPPHHPPHPPHHPPHHPPHPPHHPPHHPPHPHPHHHHHHHHHHHH - 56 (58)

 */

mod tools;
mod methods;
mod models;

fn main() {
    println!("Hello, world!");

    let mut st = models::HPmodel::State::new();
    st.molecule = "HPHHPPHHHHPHHHPPHHPPHPHHHPHPHHPPHHPPPHPPPPPPPPHH".to_string(); //first molecule

    methods::LNMCS::launch_lazy_nmcs(st.clone(),5, 20, 0.9, 20.0, 0.0, true);
    //methods::NMCS::launch_nmcs(st.clone(), 5, 20.0, true, 0.0, String::from("NMCS"));
    //methods::UCT::launch_UCT(st.clone(), 1.0, 1000000000, 20.0, 0.0, String::from("UCT"));
    //methods::BFS::BFS(st.clone(), 0.0, 0, 0.0, String::from("GBFS"));
    //methods::NRPA::launch_nrpa(3, st.clone(), 0.0, String::from("NRPA"));


}
